#[derive(Default, Debug, Clone, PartialEq, serde_derive::Serialize, serde_derive::Deserialize)]
pub struct VaccineFee {
    pub vaccine: String,
    pub fee: String,
}

#[derive(Default, Debug, Clone, PartialEq, serde_derive::Serialize, serde_derive::Deserialize)]
pub struct Center {
    pub center_id: u64,
    pub name: String,
    pub address: String,
    pub state_name: String,
    pub district_name: String,
    pub block_name: String,
    pub pincode: u64,
    pub lat: i64,
    pub long: i64,
    pub from: String,
    pub to: String,
    pub fee_type: String,
    pub sessions: Vec<Session>,
    pub vaccine_fees: Option<Vec<VaccineFee>>, // Not all centers provide this field
}

#[derive(Default, Debug, Clone, PartialEq, serde_derive::Serialize, serde_derive::Deserialize)]
pub struct Session {
    pub session_id: String,
    pub date: String,
    // FIXME: Stored as f64 due to some sessions having capacity in floats, causing decode errors
    pub available_capacity: f64,
    pub min_age_limit: u64,
    pub vaccine: String,
    pub slots: Vec<String>,
}

#[derive(Default, Debug, Clone, PartialEq, serde_derive::Serialize, serde_derive::Deserialize)]
pub struct Root {
    pub centers: Vec<Center>,
}

pub const USER_AGENT: &str =
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1";

// List of monitored districts
pub const MONITORED_DISTRICTS: [(u16, &str); 83] = [
    (8, "Visakhapatnam"),
    (49, "Kamrup Metropolitan"),
    (64, "Sonitpur"),
    (74, "Araria"),
    (86, "Muzaffarpur"),
    (97, "Patna"),
    (108, "Chandigarh"),
    (109, "Raipur"),
    (142, "West Delhi"),
    (145, "East Delhi"),
    (146, "North Delhi"),
    (150, "South West Delhi"),
    (151, "North Goa"),
    (152, "South Goa"),
    (154, "Ahmedabad"),
    (187, "Panchkula"),
    (188, "Gurgaon"),
    (192, "Ambala"),
    (195, "Panipat"),
    (199, "Faridabad"),
    (202, "Rewari"),
    (212, "Sirmaur"),
    (265, "Bangalore Urban"),
    (266, "Mysore"),
    (269, "Dakshina Kannada"),
    (281, "Uttar Kannada"),
    (286, "Udupi"),
    (294, "BBMP"),
    (296, "Thiruvananthapuram"),
    (297, "Kannur"),
    (300, "Pathanamthitta"),
    (301, "Alappuzha"),
    (302, "Malappuram"),
    (303, "Thrissur"),
    (304, "Kottayam"),
    (307, "Ernakulam"),
    (308, "Palakkad"),
    (312, "Bhopal"),
    (313, "Gwalior"),
    (316, "Rewa"),
    (348, "Guna"),
    (362, "Betul"),
    (363, "Pune"),
    (365, "Nagpur"),
    (376, "Satara"),
    (390, "Jalgaon"),
    (391, "Ahmednagar"),
    (392, "Thane"),
    (393, "Raigad"),
    (395, "Mumbai"),
    (397, "Aurangabad"),
    (446, "Khurda"),
    (453, "Sundargarh"),
    (457, "Cuttack"),
    (494, "Patiala"),
    (496, "SAS Nagar"),
    (501, "Bikaner"),
    (502, "Jodhpur"),
    (505, "Jaipur I"),
    (507, "Ajmer"),
    (512, "Alwar"),
    (513, "Sikar"),
    (521, "Chittorgarh"),
    (523, "Bhilwara"),
    (530, "Churu"),
    (571, "Chennai"),
    (581, "Hyderabad"),
    (624, "Prayagraj"),
    (650, "Gautam Buddha Nagar"),
    (651, "Ghaziabad"),
    (664, "Kanpur Nagar"),
    (670, "Lucknow"),
    (676, "Meerut"),
    (679, "Muzaffarnagar"),
    (689, "Shamli"),
    (696, "Varanasi"),
    (697, "Dehradun"),
    (709, "Nainital"),
    (721, "Howrah"),
    (725, "Kolkata"),
    (773, "Jamnagar Corporation"),
    (775, "Rajkot Corporation"),
    (777, "Vadodara Corporation"),
];
